import os
import math
import sys


def strokes_to_gcode(strokes, filename="handwriting"):
    """
    Convert stroke paths → human-like robot G-code.

    Human-motion features:
      • Smooth speed ramp  (400 → 1000 → 400 mm/min per stroke)
      • Variable pen pressure  (M3 S460 → S540 → S460)
      • Brief dwell at stroke start (pen settles onto paper, G4 P50)
      • Brief dwell before pen lift  (G4 P30)
      • Higher positional precision (2 decimal places)
    """
    gcode = []
    gcode.append("; Generated by AI Handwriting Robot")
    gcode.append("G21")         # metric (mm)
    gcode.append("G90")         # absolute positioning
    gcode.append("G1 F800")     # default feed rate

    for stroke in strokes:
        if len(stroke) < 2:
            continue

        n = len(stroke)

        # ── Pen UP → rapid move to stroke start ─────────────────
        gcode.append("M5")                               # pen up
        x0, y0 = stroke[0]
        gcode.append(f"G0 X{x0:.2f} Y{y0:.2f}")

        # Brief settle dwell (mimics human pen-placement hesitation)
        gcode.append("G4 P50")                           # 50 ms dwell

        # Initial pen-down: slightly light touch
        gcode.append("M3 S460")                          # pen down

        # ── Draw stroke with variable speed & pressure ───────────
        for j, (x, y) in enumerate(stroke):
            # smoothstep 0 → 1 → 0  along the stroke
            t         = j / max(n - 1, 1)
            curve     = 0.5 * (1.0 - math.cos(math.pi * t))   # 0 → 1 → 0

            feed      = int(400 + curve * 600)    # 400 → 1000 → 400 mm/min
            pressure  = int(460 + curve * 80)     # S460 → S540 → S460

            # Emit F and S every 6 points (strokes now have more points
            # from the smoothing pipeline, so sparser updates keep G-code compact)
            if j % 6 == 0:
                gcode.append(f"M3 S{pressure}")
                gcode.append(f"G1 X{x:.2f} Y{y:.2f} F{feed}")
            else:
                gcode.append(f"G1 X{x:.2f} Y{y:.2f}")

        # Brief pause before lift (avoids ink blob at stroke end)
        gcode.append("G4 P30")                           # 30 ms dwell
        gcode.append("M5")                               # pen up

    # ── Return home ──────────────────────────────────────────────
    gcode.append("G0 X0 Y0")
    gcode.append("M2")          # end program

    # ── Save ─────────────────────────────────────────────────────
    os.makedirs("output_gcode", exist_ok=True)
    filepath = f"output_gcode/{filename}.gcode"
    with open(filepath, "w") as f:
        f.write("\n".join(gcode))

    print(f"G-CODE SAVED: {filepath}")
    print(f"{len(strokes)} strokes → G-code ready!")
    return gcode


# ── Standalone entry-point ────────────────────────────────────────
if __name__ == "__main__":
    # Import assembler (works whether run from repo root or src/)
    _src_dir = os.path.dirname(os.path.abspath(__file__))
    if _src_dir not in sys.path:
        sys.path.insert(0, _src_dir)

    from word_assembler import assemble_human_hierarchy_text

    text = " ".join(sys.argv[1:]) if len(sys.argv) > 1 else input("Enter text: ").strip()
    if text:
        strokes = assemble_human_hierarchy_text(text)
        strokes_to_gcode(strokes, filename="my_handwriting")
